### ISSUE TITLE
Ausloggen Button funktioniert nicht

### ISSUE THREAD

**Issue by torbenf** [mPtrsn/doku-maker-app#1]
Bei Klick auf ausloggen passiert nichts. :(
Wahrscheinlich noch nicht implementiert.

Aber: 
Coole APP!!

Torben

**Comment by mPtrsn** [comment]
Das ist natürlich Absicht, damit man in der App gefangen bleibt 😄

**Comment by mPtrsn** [comment]
Fixed with [Releases v1.0.17](https://github.com/mPtrsn/doku-maker-app/releases/tag/v1.0.17)
