### ISSUE TITLE
Icons auf Buttons verschoben

### ISSUE THREAD

**Issue by torbenf** [mPtrsn/doku-maker-app#3]
Bei mir sind die Buttons verschoben :/

Galaxy S7, Android 8.0.0

![Screenshot_20210126-184252](https://user-images.githubusercontent.com/38506766/105882878-7beafc80-6006-11eb-83ab-961c4eecb25c.jpg)

**Comment by mPtrsn** [comment]
Danke! 
Aber dann ist wohl dein Handy zu klein 😁

**Comment by mPtrsn** [comment]
Fixed in new release
